name: test_swipes
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  rxdart: ^0.24.0
  shared_preferences: ^0.5.7+1
  provider: ^4.0.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
